const SeekersConst = {
  fields: [
    "FirstName",
    "LastName",
    "Email",
    "PhoneNum",
    "FatherName",
    "ContactPhoneNumber",
    "CountryId",
    "CityId",
    "StateId",
    "LoginType",
    "LastLogin",
    "Gender",
    "DateOfBirth",
    "Address",
    "MaritalStatus",
    "CVId",
    "Nationality",
    "NationalId",
    "AvailableJob",
    "ImageUrl",
    "FromSalary",
    "ToSalary",
    "SalaryNegotiable",
    "FaceBookLink",
    "LinkedInLink",
    "ProjectUrl",
    "AboutMe",
    "FirebaseUserId",
    "VerificationToken",
    "Verified",
    "IsPublic",
    "IsLocked",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {
    IsPublic: { value: true, type: "boolean", label: "IsPublic" },
  },
  order: { UpdatedAt: "desc" },
  children: [],
  top: 10,
  skip: 0,
};

const IndustriesConst = {
  fields: [
    "Title",
    "TitleEng",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {},
  order: { UpdatedAt: "desc" },
  children: [],
  top: 10,
  skip: 0,
};
const FunctionalAreasConst = {
  fields: [
    "Title",
    "TitleEng",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {},
  order: { UpdatedAt: "desc" },
  children: [],
  top: 100,
  skip: 0,
};

const EmployersConst = {
  fields: [
    "CompanyName",
    "ContactPersonName",
    "Email",
    "PhoneNum",
    "LoginType",
    "LastLogin",
    "CompanyPhoneNum",
    "CompanyLogo",
    "NumberOfOffice",
    "NumberOfEmployee",
    "OwnershipType",
    "EstablishedIn",
    "WebsiteAddress",
    "CountryId",
    "StateId",
    "CityId",
    "MapAddress",
    "About",
    "FacebookLink",
    "LinkedIn",
    "Viber",
    "Telegram",
    "ExpiredAt",
    "FirebaseUserId",
    "Status",
    "Subscribed",
    "VerificationToken",
    "Verified",
    "IndustryId",
    "ShowLogo",
    "IsFeatured",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {
    CompanyName: { value: "", type: "string", label: "CompanyName" },
  },
  order: { CompanyName: "asc" },
  children: [
    {
      name: "Industry",
      type: "no_child",
      data: IndustriesConst,
    },
  ],
  top: 100,
  skip: 0,
};

const EmployerConst = {
  fields: [
    "CompanyName",
    "ContactPersonName",
    "Email",
    "PhoneNum",
    "LoginType",
    "LastLogin",
    "CompanyPhoneNum",
    "CompanyLogo",
    "NumberOfOffice",
    "NumberOfEmployee",
    "OwnershipType",
    "EstablishedIn",
    "WebsiteAddress",
    "CountryId",
    "StateId",
    "CityId",
    "MapAddress",
    "About",
    "FacebookLink",
    "LinkedIn",
    "Viber",
    "Telegram",
    "ExpiredAt",
    "FirebaseUserId",
    "Status",
    "Subscribed",
    "VerificationToken",
    "Verified",
    "IndustryId",
    "ShowLogo",
    "IsFeatured",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],

  filter: {},
  order: { UpdatedAt: "desc" },
  childrens: [],
  top: 10,
  skip: 0,
};

const EmployerJobPosts = {
  fields: [
    "Title",
    "Description",
    "Requirement",
    "CountryId",
    "StateId",
    "CityId",
    "IndustryId",
    "JobType",
    "CareerLevel",
    "Benefits",
    "ViewCount",
    "Fromsalary",
    "Tosalary",
    "HideSalary",
    "Anonymous",
    "SalaryOption",
    "Currency",
    "NoOfPosition",
    "Gender",
    "YearsOfExperience",
    "OtherSkill",
    "Applie",
    "RejectReason",
    "Expired",
    "IsExpired",
    "JobStatus",
    "DegreeLevelId",
    "JobUnitType",
    "FunctionalAreaId",
    "EmployerId",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],

  filter: {
    Title: { value: "", type: "string", label: "Title" },
    JobStatus: {
      value: "Active",
      type: "enum",
      enum: ["Pending", "Active"],
      label: "JobStatus",
    },
    CreatedAt: {
      value: "",
      type: "date",
      lable: "CreatedAt",
    },
    IsExpired: { value: false, type: "boolean", label: "IsExpired" },
    FunctionalAreaId: {
      value: "",
      type: "foreign",
      label: "FunctionalAreaId",
    },
    JobType: {
      value: "",
      type: "foreign",
      enum: [
        "PartTime",
        "FullTime",
        "Contract",
        "Freelance",
        "DayShift",
        "NightShift",
        "Rotate",
      ],
      label: "JobType",
    },
    IndustryId: {
      value: "",
      type: "foreign",
      label: "IndustryId",
    },
    CountryId: {
      value: "",
      type: "foreign",
      label: "CountryId",
    },
    StateId: {
      value: "",
      type: "foreign",
      label: "StateId",
    },
    CityId: {
      value: "",
      type: "foreign",
      label: "CityId",
    },
  },
  order: { UpdatedAt: "desc" },
  children: [
    {
      name: "Employer",
      type: "no_child",
      data: EmployerConst,
    },
    {
      name: "FunctionalArea",
      type: "no_child",
      data: FunctionalAreasConst,
    },
  ],
  top: 10,
  skip: 0,
};

const GeneratedCvConst = {
  fields: [
    "CVFileName",
    "CVS3Url",
    "CVType",
    "Active",
    "ImageUrl",
    "CvGeneratedUIType",
    "FullName",
    "Email",
    "PhoneNumber",
    "Address",
    "Education",
    "Experience",
    "Skills",
    "Lanuages",
    "Certifications",
    "Projects",
    "ExpectedSalary",
    "Other",
    "SeekerId",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {
    SeekerId: {
      value: "",
      type: "foreign",
      label: "SeekerId",
    },
  },

  order: { UpdatedAt: "desc" },
  childrens: [],
  top: 100,
  skip: 0,
};

const AppliedJobPostConst = {
  fields: [
    "Status",
    "EmployerId",
    "JobId",
    "IsDisplay",
    "SeekerId",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {
    SeekerId: {
      value: "",
      type: "foreign",
      label: "SeekerId",
    },
  },
  order: { UpdatedAt: "desc" },
  childrens: [],
  top: 10,
  skip: 0,
};

const StateConst = {
  fields: [
    "Name",
    "NameEng",
    "Id",
    "CreatedAt",
    "UpdatedAt",
    "CreatedBy",
    "UpdatedBy",
  ],
  filter: {
    CountryId: {
      value: "",
      type: "foreign",
      label: "CountryId",
    },
  },
  order: { UpdatedAt: "desc" },
  childrens: [],
  top: 100,
  skip: 0,
};

export {
  SeekersConst,
  EmployersConst,
  EmployerJobPosts,
  IndustriesConst,
  FunctionalAreasConst,
  GeneratedCvConst,
  AppliedJobPostConst,
  StateConst,
};
